- .gitignore
- README.md
- install.cmd
- mob.go
- update.cmd
- install & update scripts for Windows added
- Readme extended
- descripton on help command extended
> Windows support

- README.md
- mob.go
My operating system does not provide say but an alternative called espeak. I therefore made the command to use for text output configurable.
> Configurable voice output program

- install.cmd
Addresses #24 by modifying script so it can run without admin permissions.
> Updated windows script to work without admin rights

- README.md
- install.sh
rationale: I do not like to install volatile dev tools in the system space. So allow the script to install the tool also into the local bin folder if no sudo rights were given
> Install in userspace

- README.md
Found a typo. Fixed it. 
Please enjoy.
> Quite is not spelled quiet

- README.md
- mob.go
- mob_test.go
hi Simon--hope this is ok. Status command was basically just showing help. I split out an "execute" function in order to make it easy to test that a command was kicked off. I also added a couple tests to verify that the appropriate message is shown when status gets executed.
> implemented status command; also added a couple tests for its output

- mob.go
- mob_test.go
A first try at implementing #14
> Start from current branch

- README.md
> Added badges for contributors and total downloads

- .github/workflows/release.yaml
> Automate homebrew releases and refactor release workflow

- README.md
I added `Version Badge` to solve the issue https://github.com/remotemobprogramming/mob/issues/72 .
Using https://shields.io/ .
And I extracted the purple color `A845E6` from mob logo image.
Someone should update `README.md` when you will release new version 👍 
Thanks :)
> Add "Version Badge" to README.md

- README.md
For some this may be obvious, for some it is just nice to have an example you can copy and paste.
> How to update using Homebrew

- mob_test.go
In order to get used to go a bit, i took a look at the tests and did some minor refactorings. let me know if this works for you
> Minor test refactorings

- go.mod
- mob.go
- mob_test.go
The go.mod file helps with IntelliJ.
It enables to show code coverage and debug tests.
Maybe you want to change the module naming.
With the help of your tests I did more refactoring.
Was focusing on determineBranches.
I did many smaller commits, so it is more comprehensible.
> Adds the go.mod file, and further refactoring

- README.md
See https://github.com/remotemobprogramming/mob/issues/101 for details.
> README: add arch package installation instructions

- README.md
add 2 arch packages: mobsh and mobsh-bin
See https://github.com/remotemobprogramming/mob/issues/101 for details.
> README: update arch package installation instructions

- .github/build
See https://github.com/remotemobprogramming/mob/issues/105
> add LICENSE to tarball

- mob.go
- mob_test.go
improves determineBranches again, but keeping the dualism
testing removeWipQualifier at a better abstraction
> introduces configuration as parameter to start and subsequent functions

- mob.go
- mob_test.go
introduces new method configuration.hasCustomCommitMessage
> next and subsequent functions take configuration as a parameter

- .gitignore
- CHANGELOG.md
- README.md
- mob.go
> Allow setting a default timer duration via MOB_TIMER env variable

- README.md
- mob.nix
Added nix expression to readme.
> Added nix expression to readme.

- README.md
- mob.nix
To configure espeak for TTS, pass withSpeech = true to the package call.
> Added optional espeak dependency to nix package.

- README.md
- go.mod
> go.mod: fix executable name, lower expected version to 1.14

- mob.go
I like it better this way. what do you think?
> refactor parseArgs

- CHANGELOG.md
- mob.go
- mob_test.go
Let me know if this makes sense as a first start to fixing this issue.
> issue #156 - prevent mob session with outstanding local commits

- coauthors_test.go
- mob_test.go
- squash_wip_test.go
> Tests don't share configuration anymore

- README.md
- snap/snapcraft.yaml
> global gitignore in snap

- CHANGELOG.md
- mob.go
- mob_test.go
This is going in the suggested direction.
> Multiple wip branches

- mob.go
Hi Simon,
This PR resolves two issues that `staticcheck` found and reported in Visual Studio Code. I figured I'd raise this separately so it doesn't get mixed in with any upcoming changes.
Thanks and have a great day!
> style: Remove unnecessary fmt.Sprintf

- README.md
Let's remove that test detail.
This closes #204.
> docs: Remove command that is already called in mob_test.go

- README.md
> Update installation instructions using go

- CHANGELOG.md
- mob.go
How can one be happy collaborating without seeing a smiley face? 
This PR simply adds that smiley face to make your day :)
> Add smiley face to Happy Collaborating message

- CHANGELOG.md
- README.md
- mob.go
- mob_test.go
> first try at the clean command

- CONTRIBUTING.md
When creating my first PR I ran into some (minor) issues because I did not see that some command or options existed. After resolving these things, I decided to write a short documentation on how to contribute.
Please check if the version numbers, requirements, the DCO and so on are ok! And feel free to change or add anything.
Signed-off-by: Thomas Much <github@snailshell.de>
> Add documentation on how to contribute

- README.md
discussion around this change occurred in #274
> Add instructions for integration with timer.mob.sh

- CHANGELOG.md
- mob.go
Hi, I've decided to help a little with https://github.com/remotemobprogramming/mob/issues/288 
I'm not sure if that's what you meant but feel free to correct me
> ISSUE-288: Update 'git' not installed error message

- CHANGELOG.md
- README.md
- mob.go
- mob_test.go
add --create functionality in the simplest form as described in #211
> add function mob start --create

- CHANGELOG.md
- mob.go
- mob_test.go
> added reset warning and delete-remote-wip-branch parameter

- create-testbed
- mob.go
- mob_test.go
Hello, this PR fixes issue #302 .
Don't hesitate to give your feedback if you think I should change something!
> fix gitRootDir() to allow usage of symlinked .git folder

- CHANGELOG.md
- mob.go
- mob_test.go
- test/test.go
I added the functionality that local timers will be aborted if a new timer is set or if the commands mob next or mob done were executed.
> Better timer

- configuration/configuration.go
- configuration/configuration_test.go
- mob.go
- mob_test.go
- squash_wip_test.go
added a config variable to customize git push options on mob branch.
> Git push options

- README.md
[Amadeus](https://amadeus.com/) is a proud user of mob in our remote teams part of our cloud migration program
> Amadeus as user

- README.md
- configuration/configuration.go
- configuration/configuration_test.go
- mob.go
- mob_test.go
- squash_wip.go
- squash_wip_test.go
> feat: allow configuring mob start commit message

- mob.go
- mob_test.go
> #358 fixed printing git merge just once in mob done

- .github/build
- .github/workflows/release.yaml
> #352 macOS universal build

- CHANGELOG.md
- README.md
- help/help.go
- mob.go
- mob_test.go
- open/open.go
- open/open_darwin.go
- open/open_linux.go
- open/open_windows.go
> #356 open timer in web browser

- mob.go
- mob_test.go
> #303 better error message if repo does not have any commits

- mob.go
- mob_test.go
> #346 fixed bug that mob thinks there is something to commit if git configuration status.branch is true

- mob.go
- mob_test.go
> fix mob clean

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .github/workflows/virustotal.yaml
- go.mod
- mob.go
- mob_test.go
> fix the logging how to fix uncommited changes

- mob.go
- mob_test.go
> Fixes a bug where git hook is not ignored on start

- README.md
Update minimal go version needed to build and install from source.
Update mob version from v3 to v4.
> Update README section Using go tools

- CHANGELOG.md
- mob.go
- mob_test.go
> #406 - removed cancelation of mob timers

- mob.go
Improving this so I can wrap my head around it when creating a thefuck rule
> Refactor sayFixUncommittedChanges

- mob.go
Addresses https://github.com/remotemobprogramming/mob/issues/372
> Print Git Commands before they are run

- CHANGELOG.md
- README.md
- help/help.go
- mob.go
This issue was reported by @stefanscheidt in [Slack](https://mobsh.slack.com/archives/C06UM83BKPX/p1727248697230289?thread_ts=1726815243.824169&cid=C06UM83BKPX)
> fix documentation of mob start --discard-uncommitted-changes

- README.md
> fix slack badge
