remotemobprogramming/mob

- README.md
Slightly related to #8, with regards to how one can configure the process.
> Add pointers on how to configure `mob`

- mob.go
The `join` option is gone, so it shouldn't appear in the help text
> Remove help description for `mob join`

- mob.go
Squashing is not allowed unless fast forward is used as merging strategy. FF is the default, but could be overridden in `.gitconfig`, and hence it could be nice to correct this when running the automated command.
How to disable fast forward in `.gitconfig`:
```gitconfig
[merge]
ff = false
```
If you have disabled FF you will get the following error when running `mob done`:
```
...
[git merge --squash mob-session]
fatal: You cannot combine --squash with --no-ff.
⚡ [git merge --squash mob-session]
⚡ exit status 128
```
> use fast forward when squashing

- install
My default shell is not bash compatible and the install script failed. The shebang would guarantee a correct interpreter being used.
> Run the install script in the correct environment

- mob.go
Hi @simonharrer,
thanks for creating the remote mob programming tool.
When we started using it, we quickly ran into the issue that the `mob next` commits were rejected by our rather strict git pre-commit hook. Since we don't want to get rid of the hook and you mentioned [here](https://github.com/remotemobprogramming/mob/pull/16#issuecomment-599636689) that you agree that always using `--no-verify` makes a lot of sense for work-in-progress commit, I've add the (hard-coded) flag.  Making it a configurable option is imho not worth the added complexity.
> Always commit the "mob next" commit with --no-verify to skip pre-commit hooks

- README.md
- mob.go
Actually there is a way to make the zoom screenshare work on Linux as well. It depends on `xdotool`.
> Add linux support for share

- install
When I tried to install `mob`, I got a bunch of Go compiler warnings, but it still said it installed `mob`. This was pretty confusing.
This change conditions the "success" message on the successful compilation and copying of the compiled file.
> Only print "success" when successfully installed

- README.md
I tried to make Direct Share global which does not have such a checkbox.
Mentioning the shortcut name explicitly might help others.
@jlangr gave me the tip how to solve this
https://twitter.com/jlangr/status/1255853376891322368?s=20
> Rephrase zoom screenshare section

- README.md
- install.sh
Rationale: 
While using the WSL is a nice alternative, not everyone can install it (company policies, availability of the hypervisor, etc). As most Windows devs should have a git installation (if not, they can't work with `mob` anyways :wink:) it would be nice support installing mob via the git-bash that comes bundled with it.
Pros:
* no extra effort required for maintaining a install.cmd script
* user can install mob very easily
* shell syntax much better than the horrible Batch syntax
* external tools in the installer such as tar, tr, curl also bundled within git-bash
* no GoLang binary required for installing mob
Cons: 
* user feels comfortable in Windows and does not move to a better OS, such as OSX or Linux :wink:  
* PowerShell might be a feasible alternative. But it has still the …
> Windows git bash installation

- install.sh
There is a slight error in the installer that makes it impossible to install mob into user space. I fixed it here
> fixed user flag for non-windows systems

- README.md
- mob.json
Created a scoop "app manifest" file which will allow Scoop to install mob on Windows. There is more that could be done for more in depth scoop support for versioning , etc, but it's a step towards that - and it works.
Scoop has the concept of buckets, and you can make your own or contribute to them, so this could be something to add to the 'extras' bucket, or possibly create a new one for mobbing / remote work / etc., which would remove the need to get the mob.json file manually.
Also updated the readme and provided a link to the Scoop site for more information.
The link is hard-coded to the 64 bit windows version - there is support to add 32/64 sections if that seems valuable.
> Scoop installer

- .github/workflows/ci.yaml
- README.md
This is a first simple try to adding a CI workflow, that runs all the tests. 
A badge is available here https://img.shields.io/github/workflow/status/remotemobprogramming/mob/ci, so this could help to see if the tests on master are currently passing or failing.
I am not sure, if those tests should also be added to the release workflow. I feel that no commit should make it to master, that is not passing the tests. But I am sure this is strongly opinionated, as I am used to working like this, so feel free to make comments about this. 
I am new to GitHub Actions, but so far I could not find a way of adding the tests to the Release workflow without copy and pasting all of the steps.
Fixes #59
> Add CI workflow

- .github/build
- .github/workflows/release.yaml
- .gitignore
fixes #69 
I have chosen the golang-action because it takes care of setting up the go workspace. I moved the code that takes care of creating the tar.gz and checksum files into this repo inside the .github folder. 
You can now retire the go-release.action fork.
> Remove go-release.action and move artifact code to this repo

- CHANGELOG.md
- mob.go
- mob_test.go
I implemented this Issue #61 because it's so useful for our usage.
Based on your idea, I fixed mob next to push if the current mob branch and remote commit hash are different.
> On second thought, one could locally check if origin/mob-session and mob-session deviate and only if they point to two different commits initiate a git push.
> Update mob next to push manual commits

- mob.go
Hey, love your tool - we're using it since a week back and it's really helping us!
I found that I didn't want the voice notification, only the text notification.
The current implementation doesn't continue with the notification command unless the previous (voice) has finished with an exit code 0, which it doesn't unless you have it configured properly.
My proposed changes include
- run all the commands, voice & text regardless if the previous exited ok
~~- add an additional env variable `MOB_NOTIFY_COMMAND` to allow specifying the notification command~~
~~- a small refactoring related to how commands are collected and executed cross platform~~
The last two changes are moved to a separate PR #80
> Continue with next notification command even if the previous failed

- mob.go
- add an additional env variable `MOB_NOTIFY_COMMAND` to allow specifying the notification command
- a small refactoring related to how commands are collected and executed cross platform
> Support to specify notify command

- install.sh
I had a manually installed version on my machine that was preferred over the one that was installed by `install.sh`. I didn't notice that for quite a while, because it wasn't obvious from the scripts' output.
This PR adds a check for that and will echo a warning if the `mob` binary ist not at the expected location. I tested it on my machine (Ubuntu 20.04), not sure if this works on all platforms.
> After installing, check if the mob binary is at the expected location

- mob.go
The old behavior of `MOB_WIP_BRANCH` was important for us, since we have multiple teams collaborating on a single codebase.
While it's technically possible to keep multiple branches going with the `-b` flag, having to specify the same branch every time is tedious.
This adds a new environment variable, `MOB_WIP_BRANCH_QUALIFIER`, that allows you to set a default branch qualifier.
Setting a value on the command line overrides the environment variable, allowing you to specify a different wip branch.
To use the default branch when the `MOB_WIP_BRANCH_QUALIFIER` environment variable is set, you can specify `-b ""`
> Read WIpBranchQualifier from an environment variable

- README.md
- create-testbed
When I followed the "How to contribute" instructions as is, I couldn't run the tests. I learned that I need to run the `create-testbed` script, but when I ran that script, it failed. I believe that this PR fixes both problems.
> Improve instructions for how to contribute

- mob.go
- mob_test.go
Uses [SubTests](https://golang.org/pkg/testing/#hdr-Subtests_and_Sub_benchmarks) to parameterize all expectations for boolean typed environment variables. To test all cases for a single boolean environment variable all it needs is a single line of code.
It indents the cases nicely
Also it does not fail all Tests.
In the following example i have only implemented the default of MOB_DONE_SQUASH wrong
> Found a way to parameterize the Environment Variable Tests

- mob.json
- Bump mob from 0.0.24 to 1.1.0
- Add scoop autoupdate url + hash
- Add hash + license + description
I gave the scoop manifest of mob a bit of ❤️  (its now autoupdatable using [checkver.ps1](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#updating-manifest) of scoop).
I considered adding mob to the scoop main bucket (and opening a PR there as well) as it's a bit cumbersome to download the json just to install mob using scoop. 
> Update scoop manifest

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- create-testbed
- go.mod
This should fix #127 fix #134 and fix #98 
I simplified the actions by moving the git config part to the create-testbed script. I think this reflects, that the git config is indeed a requirement for successfully running the tests. This allows to use the golang actions for the tests as well. Since the actions are run in separate docker containers, there is no way to run the git config commands through the action. The benefit of this is, that the ci action is now very similar to what happens during the release, so potential errors could be caught well before an actual release is created.I have sucessfully created a test release in my fork, check it out here: https://github.com/Morl99/mob/releases/tag/1.3.5
Let me know if that makes sense to you or if you'd want to change something.
> Upgrade to Go 1.16 using Go Module

- CHANGELOG.md
- mob.go
- mob_test.go
See https://twitter.com/Morl99/status/1365360716610478080 for the discussion about the feature
I am very new to go and would happily take any comments about how this code could be simpler, if possible. 
I decided to write a test for the "happy" case, where the new code actually makes any difference, and decided that for everything else, the existing tests are good enough.
@simonharrer do you think that this should be configurable behaviour? Can you think of a use case, where mob should consistently print the whole list, or more than 5 entries? 
PS: I was unable to execute the commans that are documented in the "How to contribute section", as Go always complained about a missing module. I readded the module file that you created yesterday and it worked like a charm. I am using go 1.16, not …
> Truncate list of last commits if it is longer than 5 entries

- create-testbed
- mob_test.go
- in support of coauthors efforts (#144, #121, #81) per request from @lamalex 
- also creates the /tmp/mob/notgit subdir
- includes a simple test case for the testbed itself
- includes the code allowing run() to return a string, and a test case for same
> refactor create-testbed to create more repos

- CHANGELOG.md
- coauthors.go
- coauthors_test.go
- create-testbed
- mob.go
- mob_test.go
In draft mode for discussion:
- fixes #81
- includes a TestStartDoneCoAuthors() test case
- includes a refactored create-testbed that adds more local repos and sets unique committers in each to exercise coauthors code
Implementation in mob.go will need (approximately):
- an appendCoAuthors() function, called by done(), modeled after the bash code in https://github.com/remotemobprogramming/mob/issues/81#issuecomment-770440672 
- include a "Co-authored-by: Dustin McQuay <dmcquay@gmail.com>" header in this commit
- a gitLogCoAuthors() function, modeled after gitBranches(), called by appendCoAuthors().  We would call the following `git log` command to get the list of authors on the mob branch, splitting each resulting line on comma to get the username and email.  We would also need to remove …
> Automatically append `Co-authored-by:` lines after squash

- README.md
I tried this method and it worked well. Seems more idomatic these days for go-based tools.
The `go install` command does a `go build` (figuring out binary name based on folder name and/or package name) and then moves the binary to the bin folder under your `GOPATH`
> update install instructions with go install

- create-testbed
This commit ensures the createtestbed creates and
checks out the specific branch expected by the
tests, even when the local git client is configured
with a different default.
Previously the createtestbed script not being
explicit about branch names when creating it's first
commit so would inherit the default branch name
which you have configured in your local git client
If, for example, you have configured your local git
client to use 'main' as the default branch name, then
the createtestbed script was creating repos under
/tmp/mob/... which had 'main' as the default branch
name
The tests, however, are still hard-coded to a legacy
assumption about the default branch name and so
could fail like this:
SET WORKING DIR TO /tmp/mob/local
======================
mob_test.go:981:
exp: "on branch …
> GH-160 fix createtestbed to match tests

- mob.go
The help text "To finish, use git commit" should only be shown when the commits are squashed. When merging it is not necessary to commit.
> Say "git commit" only on squash

- README.md
- snap/local/mob-launcher
- snap/snapcraft.yaml
- automatic connection of gitconfig has been granted, removed manual connection from README
- automatic alias to mob has been granted, removed manual alias creation from README
- automatic connection to ssh-keys has been rejected, manual connection is checked in mob-launcher
- bump version to 1.6.0
> snap update

- CHANGELOG.md
- find_next.go
- find_next_test.go
- mob.go
The existing heuristic which suggests the next mobber is relatively simple. The PR tries to add some improvements, namely:
* Do not suggest the current Git user if there are other mobbers in the list.
* Do not list the name of a previous committer multiple times in a row.
* Apply a simple lookahead in order to also suggest persons which might have been absent in the previous mob round.
Hopefully the tests make my intensions clear.
> Improve next mobber suggestion

- mob.go
- mob_test.go
- squash_wip.go
- squash_wip_test.go
I introduced a Value Object `Branch`.
See where this is going?
Some of the behavior of `Configuration` moved to `Branch` where it is more appropriate.
`Branch` could even accumulate more behavior such as `checkout` and many more.
While it's tempting to move some git wrapper functions into `Branch`, I think this should only be a temporary solution.
At one point we probably want a git interface that abstracts away all git functionality.
Once we have that, git should be passed as an argument to branch.
E.g.
```
git = newGitCliWrapper()
newBranch("mob-session").checkout(git)
```
I see many advantages in this design.
> Branch value

- mob.go
- mob_test.go
This PR implements the feature requested in #197:
> Given there are no squashed changes made on a branch  
> When a user runs `mob done`  
> Then it should show an info message
<br>
**Demo:**
https://user-images.githubusercontent.com/2585460/139372391-a7063a7f-1d2d-4d04-a43f-b590d8272616.mp4
<br>
**Test Plan:**
It has been manually tested and unit tested.
> Improve message when there is nothing to commit

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
The `cedrickring/golang-action` GitHub Action has been deprecated and will not be maintained to support new versions of Go beyond v1.16. This PR switches to the official `actions/setup-go` action.
**Notes**:
- `cedrickring/golang-action` uses the latest patch version (for example, 1.16.x). To reproduce this behaviour we need the `~` in `~1.16.0`.
- The new action makes it even easier to set up a build matrix to get many versions of Go
This PR closes #205.
> chore: Switch to the official actions/setup-go GitHub Action

- README.md
This is a quick edit to the docs. The separator changed in v1.0.0 from `/` to `-`.
> docs: Update the separator from `/` to `-` to match current behaviour

- README.md
Since there is no more package `mobsh` (we only provide `mobsh-bin`) we should probably also remove the reference from the README.
> README: remove obsolete reference to arch/aur

- .github/workflows/release.yaml
This PR fixes the checksum used for the Arch Linux release and should resolve #227.
**Root cause:**
- The SHA checksum was only calculated for the MacOS release.
**Proposed Changes:**
- Calculate the checksum for both MacOS (darwin) and Linux.
- Use the MacOS checksum for `brew`
- Export the Linux SHA checksum from the `release` job so it can be used in the `publish-arch-linux-package` job.
**Test Plan:**
:warning: I have not tested this change yet. Based on how we handled this previously, I'd suggest we create a 2.2.1 release and I'll manually confirm that Arch Linux and `brew` work as expected. What do you think @simonharrer?
> Fix the SHA checksum used for the Arch Linux release

- CHANGELOG.md
- README.md
- coauthors_test.go
- mob.go
- mob_test.go
- squash_wip.go
- squash_wip_test.go
Adds new `mob done --squash-wip` option, which does a `mob done` but also runs `squashWip` beforehand.
As a result, when you use `mob done --squash-wip`, you can keep the manual commits you made on the wip branch while getting rid of all the wip commits.
`squashWip` had to be tweaked for this to fixup subsequent wip commits that had no following manual commit. And it also undoes a final wip commit, so that the user is forced to commit those changes manually.
The environment var MOB_DONE_SQUASH is made backward compatible, while the `.mob` config file does not support activating --squash-wip yet.
Questions:
- Should we now already discard the `mob squash-wip` command after all?
- Can you find any corner cases I missed?
> Squash wip improvement

- mob_test.go
We had one test, which asserts an error message of git. If your os uses a different language setting the english, this test will fail. I adjusted the test to use the mob specific error message.
> adjusted test to assert mob error message instead of git error message

- .github/build
Fixes #240.
Please have a look. I tested this on my fork.
See the names of the files in the test release on my fork: https://github.com/jomora/mob/releases/tag/testsha256. 
(I'll delete the fork after the PR gets approved. So the link won't be valid anymore afterwards.)
> Issue 240: Use SHA256 instead of MD5 for signing

- CHANGELOG.md
- mob.go
- mob_test.go
In #253 the feature is mentioned that the three new DoneSquash values can be set via env var right now. This PR allows setting these values via config file, too.
Note: there is a change in behaviour if a garbage value is passed. Before we would issue a warning. Now we match the env var behaviour (no warning, set "squash" value).
Signed-off-by: Thomas Much <github@snailshell.de>
> Allow setting DoneSquash values via config file

- mob.go
- mob_test.go
With #256 it was possible to set the DoneSquash values via config file. However, this only worked for unquoted values. Now both unquoted and quoted values are supported.
The unquoted variant is still necessary for backwards compatibility when boolean values are assigned.
Signed-off-by: Thomas Much <github@snailshell.de>
> Support both unquoted and quoted DoneSquash values in config file

- README.md
Autocompletion for `mob` is available in the latest stable release from "fig" now.
Is this link enough (IMHO yes)? Or should I supply a screenshot as well?
> Add link to fig shell autocompletion

- CONTRIBUTING.md
I've added a section about how to switch back to the official `mob` release after you've built & installed the project locally.
I stumbled over this after my PR, so it might be helpful to others.
If there's a better solution, feel free to change the section.
And if this is too trivial or too specific, feel free to reject this PR.
> Update documentation on how to contribute

- CONTRIBUTING.md
- README.md
- mob.go
I documented the already existing short command aliases in the README and in the man page.
Is this too verbose, too long output? I tried something like
"For some commands there are short aliases available: s (start), n (next), d (done), b (branch), t (timer)"
as a single line below the "Add --debug ..." line. But I think the longer form in this PR is more readable.
> Document short command aliases

- README.md
I updated `go install` installation instruction in README to `v3`, which is the latest major version
> Update go install instruction to v3

- install.sh
Relates to #276 
Gave some hints to the user about what could be the issue and hid the false error message about duplicate binary.
Minor formatting about doc reference as it was not clear that the link was related to the above text.
> Clarifying error when mob isn't found in PATH

- README.md
I've created [a Chocolatey package for mob](https://community.chocolatey.org/packages/mob) and thought it might be helpful to add a reference in the README. Thanks!
> Add reference to Chocolatey to install on Windows

- CHANGELOG.md
- mob.go
- mob_test.go
As a naïve user (no remembering that the tool has only one help page) I expect to get some help for the `start` command (options that can be specified) when executing `mob start --help`. Instead, a mob session started requiring some manual clean-up from my part afterwards.
I would like to change the behavior in the way that whenever there is some help option in the command, the tool prints the help page.
> Show help output whenever any kind of help argument is given

- mob.go
This is a follow-up of dae1648cc46fd which missed this location.
> Use WIP branch separator in help output

- CHANGELOG.md
- mob.go
- mob_test.go
- squash_wip.go
Found and addressed a bug where when one of the mobbers has had an unpushed commit thus other mobbers were behind on the base branch. They ran into a problem when they would do `mob done --squash-wip`
> Test behaviour on pre existing commits

- CHANGELOG.md
- find_next.go
- find_next_test.go
- mob.go
- Show list of last committers only if there are any
- Skip suggestions if there has only been a single person so far
- Consider the case of a new typist joining the session
- Fix reporting on first commit
- Rename mobber to typist
> Various fixes in suggestion of next typist

- CHANGELOG.md
- mob.go
I've added a check for git availability in `getMobTimerRoom` method to allow it to work anywhere in the system.
So, now the behaviour is like this:
- If git repository -> works as it worked before
- If not a git repository -> use the room name from `MOB_TIMER_ROOM` 
---
I wonder if the code, especially `mob.go` file, shouldn't be somehow split into smaller files? It's slightly difficult to work with.
I have not much experience in Go and maybe that's not a good idea to separate all that stuff? I feel like it would make it easier to test it at least.
> [#293] Mob timer should work anywhere on the system

- mob.go
It may happen that the SSL verification fails when the mob user has a bad setup in combination with an stupid enterprise network which does SSL interception.
To circumvent that I added a new CLI parameter which makes it possible to disable the SSL verification.
This CLI parameter should only be used when the user is sure what he/she is doing since it could be a security risk to not to verify the certificate.
See the screenshot of how it works:
> Add a new command line argument for for disabling SSL verification

- README.md
as the old link was pointing to the current volume and not the one that featured mob
> fixes typo and adjusts link to tech radar

- coauthors.go
- mob.go
- mob_test.go
- say/say.go
- squash_wip.go
> Refactor: Extract say to its own file

- mob_test.go
- test/test.go
Notice, the failing Test now says why it fails:
`expected 'exactly 1 mob timer process found' to occur within 2s but did not: goroutine 5588 [running]:`
> Improve await feedback

- README.md
> fix the example in man page.

- mob.go
- mob_test.go
This PR changes `currentCliName` to use `path/filepath` for path manipulation and closes #322 .
> Fix cli name detection on Windows

- squash_wip.go
This PR fixes #336 by using the `currentCliName` to trim the excess ".exe" part of the executable name in `isTestEnvironment`.
It also fixes the path separators in the command returned by `mobExecutable`, so they work correctly in the git bash environment they are going to get executed at.
> Fix squash wip tests on Windows

- coauthors_test.go
- mob_test.go
This PR fixes #339. It removes the `run` function from `mob_test.go` and replaces the usages with go `os.*` calls.
The PR also fixes `gitRootDir()` comparisons on Windows and the Unix `touch` utility usage in `TestStartNextStay_DoNotWriteLastModifiedFileInCommit_WhenFileIsMoved` .
> Fix tests on Windows

- mob.go
- mob_test.go
This PR fixes #332 by adding the checks for the required minimum version.
I used a bit more lenient regexp for parsing the git version, since git version strings can be customized during the git commands `./configure` step.
I'm not a 100% sure about adding `minimumGitVersion*` to the const section, adding a single GitVersion struct would have been more elegant, but that can only go in the golbal var section.
> Check if git version is at least 2.13.0

- mob.go
- mob_test.go
Fixes #348 by pulling before squashing.
It's a very simple fix.
Another Idea would be to warn the user that they didn't start or something. 
But that might be more complicated.
> Fixes Squash wip losing changes without start

- .github/workflows/release.yaml
Due to deprecation of `save-state` and `set-output` commands in GitHub Action workflows, this PR should prevent workflows to fail after the 31st May 2023.
Link to GitHub blogg:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
fix #379
> fix: deprecated set-output in GitHub Action workflows

- mob.go
- mob_test.go
Users who have the Git config push.default=tracking, or other values, will have different default behavior on 'git push'.
Example: a newly created mob branch from `origin/mainline` is tracking `origin/mainline` until `--set-upstream` takes effect. The original `git push`, which is intended to push to `origin/mob/mainline`, will actually push the `mob start` commit to `origin/mainline` if `push.default=tracking`.
To avoid this scenario, we will always specify the remote ref we are pushing to.
> Directly specify remote ref when pushing.

- mob.go
- mob_test.go
This is my attempt to allow opening last modified files when the project path on disk contains spaces. I also opened issue  #387 with further details.
The test I added works with a last modified file containing spaces instead of a project path containing spaces, as this was way easier to set up for me and seems to exhibit the same behavior.
As I have no prior experience with Go, I assume my code is not idiomatic. Also, I have not yet extracted functions yet. Therefore, feedback about how my code better fits into the codebase is greatly appreciated.
> Open last modified file with spaces in path

- mob.go
- mob_test.go
- status.go
- status_test.go
closes #410 
the result of the change can be seen here. 
```
$ mob status
> you are on base branch 'main'
> remote wip branches detected:
- origin/mob/main (10 months ago)
- origin/mob/main-my-feature (1 year, 4 months ago)
```
if there is no remote wip branch:
```
$ mob status
> you are on base branch 'main'
> no remote wip branches detected!
```
> #410: added duration to latest commit for a remote branch to mob status

- configuration/configuration.go
On Windows, I am seeing long command times (10+ seconds) when running mob. I was able to narrow it down to the `user.Current()` call. I assume it takes a long time because my Windows user is managed by an organization domain controller. Switching to `os.UserHomeDir()` fixes this performance problem and `user.Current()` uses that under the hood anyways: https://github.com/golang/go/blob/974b2011ca2a74ca1137558771b428bddb2e7df3/src/os/user/lookup_stubs.go#L32.
> Use os.UserHomeDir() instead of user.Current() HomeDir to improve Windows performance

- configuration/configuration.go
- configuration/configuration_test.go
- mob.go
- mob_test.go
- squash_wip_test.go
- status_test.go
- test/test.go
In this PR i will remove this empty commit when doing mob start as this can lead to branches where someone did a mob start and did not work there and after few weeks we revisit the project and do mob start and do not notice that this is a running session with just the empty commit. 
The main reason for this empty commit was optimization of ci runs. We could again introduce the ci.skip push option and give the user the option to either disable it or to explicitly enable it. I think in the most cases this should not make any problems and could be held that we have a option to disable the option. 
The CI skip options would for example not work on github, but should not be any issue adding the option there. It just will not skip the ci. This is something which hurts less than the empty …
> WIP: remove empty commit on mob start

- README.md
Let's add our usage to the Readme (as discussed in a conversation with @simonharrer during the JAX in Mainz).
> Add reference to DB Systel in "Who is using 'mob'?"

- CHANGELOG.md
- configuration/configuration.go
- configuration/configuration_test.go
- mob.go
- mob_test.go
> #446 mob start --discard-uncommitted-changes

- install.sh
Closes #452
When installing on Windows via git bash, `command -v mob` gives a UNIX style path while `$target` gives a UNIX style path but with a Windows style drive lettering (e.g. "C:/..."), leading to a mismatch.
This patch checks if the system is Windows, and if so, converts the expected path to the same format (Windows style drive lettering, forward slashes) before comparison.
> Fix #452 installed binary path check on Windows git bash

- install.sh
`==` for string equality is non-POSIX. One `=` suffices.
> Check string equality more portably.

- goal/goal.go
- httpclient/httpclient.go
- timer.go
This is a tiny change that refactors httpclient to:
1. Remove `getHttpClient` (which was unused).
2. Inject a `*http.client` into `SendRequest`, rather than having `SendRequest` self-initialise one.
3. Have usages of `SendRequest` initialise a `http.client` using `GetHttpClient`
In terms of logic, things are the same as they were before, with the exception of the request being initialized _after_ the client, instead of before.
Now that `SendRequest` is decoupled from `http.DefaultClient`, it's a little easier to write unit tests for it (which I'd be happy to do)
I'd be super interested in your thoughts on the general theme of doing dependency injection like this.
> Inject http.client into httpclient.SendRequest

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- configuration/configuration.go
- configuration/configuration_test.go
- help/help.go
- mob.go
I've added a shortcut for `mob start --create` as `mob start -c`
The "configuration/configuration_test.go" has not been executed with `go test -v`, thus I updated the README with `go test ./...` to run tests in all modules.
Regarding the version update: I was not sure, how your updates work exactly. I've included it in this PR, feel free to remove or update, as you see fit.
> feat: add shortcut for `--create` as `-c`

- README.md
Now that `mob` is available from the official Homebrew repository, we can recommend to install it from there. Works for Linux and macOS.
> Update Homebrew installation and fix a few typos
